---
# Lint Ansible playbooks (we need to call all of our top-level playbooks 'playbook.yml')
ansible-lint:
  image: registry.gitlab.com/alexhaydock/ci-linter-images/ansible-lint
  stage: test
  script:
    - for i in $(find . -name "playbook.yml"); do ansible-lint "${i}"; done

# Lint all Dockerfiles in this repo (any Dockerfile, recursively)
docker-lint:
  image: projectatomic/dockerfile-lint
  stage: test
  script:
    - for i in $(find . -name "Dockerfile" -or -name "Dockerfile*"); do dockerfile_lint -f "${i}"; done

# Lint Terraform files inside top-level directories in this repo
terraform-lint:
  image: registry.gitlab.com/alexhaydock/ci-linter-images/tflint
  stage: test
  script:
    - for i in $(find . -maxdepth 1 -mindepth 1 -type d -not -name .git); do (cd ${i} && /opt/tflint); done

# Lint all YAML files in this repo (any yaml file, recursively)
yaml-lint:
  image: registry.gitlab.com/alexhaydock/ci-linter-images/yamllint
  stage: test
  script:
    - for i in $(find . -name "*.yml" -or -name "*.yaml"); do yamllint "${i}"; done
