---
__hostname: "{{ lookup('env','TF_VAR_DESIRED_HOSTNAME') }}"
__domain: "{{ lookup('env','TF_VAR_DOMAIN_NAME') }}"
__fqdn: "{{ lookup('env','TF_VAR_FQDN') }}"
__letsencrypt_email: "{{ lookup('env','TF_VAR_LETSENCRYPT_EMAIL') }}"

# Once we've installed Python 3 during the first playbook run (assuming CentOS 7)
# we can use it for this second playbook:
ansible_python_interpreter: /usr/bin/python3
...
