---
- name: Install Docker and Pip
  become: true
  package:
    name:
      - docker.io
      - python3-pip
    state: present

- name: Install Pips for managing Docker
  become: true  
  pip:
    name:
      - docker
      - docker-compose
    state: present
...
