---
- name: Install Docker and Pip
  become: true
  apt:
    name:
      - docker.io
      - python3-pip
    update_cache: true
    state: present
  tags:
    - docker

- name: Install Pips for managing Docker
  become: true
  pip:
    name:
      - docker
      - docker-compose
    state: present
  tags:
    - docker
...
