---
- hosts: all
  name: Pi-Hole
  gather_facts: true


  roles:
    - role: fix-ubuntu-system-dns
      when: ansible_distribution == "Ubuntu"

    - add-sshfp-record
    - acme-tls-cert
    - deploy-pihole
...
