---
version: '3.7'
services:
  wp-db:
    image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    container_name: wp-db
    restart: unless-stopped
    environment:
      - "MYSQL_ROOT_PASSWORD=somewordpress"
      - "MYSQL_DATABASE=wordpress"
      - "MYSQL_USER=wordpress"
      - "MYSQL_PASSWORD=wordpress"
    volumes:
      - wordpress-db:/var/lib/mysql
    networks:
    - webserver-net

  wp-web:
    depends_on:
      - wp-db
    image: wordpress:latest
    container_name: wp-web
    restart: unless-stopped
    environment:
      - "WORDPRESS_DB_HOST=wp-db"
      - "WORDPRESS_DB_USER=wordpress"
      - "WORDPRESS_DB_PASSWORD=wordpress"
      - "WORDPRESS_DB_NAME=wordpress"
      - "VIRTUAL_HOST={{ __domain_name }}"
      - "LETSENCRYPT_HOST={{ __domain_name }}"
      - "HSTS=max-age=31536000; includeSubDomains; preload"
      - "SSL_POLICY=Mozilla-Modern"
      - "ENABLE_IPV6=1"
    volumes:
      - wordpress-web:/var/www/html
    networks:
      - webserver-net

  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:80/tcp"
      - "0.0.0.0:443:443/tcp"
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - /data/proxy/conf:/etc/nginx/conf.d
      - /data/proxy/vhost:/etc/nginx/vhost.d
      - /data/proxy/html:/usr/share/nginx/html
      - /data/proxy/dhparam:/etc/nginx/dhparam
      - /data/proxy/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - webserver-net

  letsencrypt:
    depends_on:
      - nginx-proxy
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: nginx-proxy-ssl
    restart: unless-stopped
    volumes:
      - /data/proxy/conf:/etc/nginx/conf.d
      - /data/proxy/vhost:/etc/nginx/vhost.d
      - /data/proxy/html:/usr/share/nginx/html
      - /data/proxy/dhparam:/etc/nginx/dhparam
      - /data/proxy/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - webserver-net

volumes:
  wordpress-db:
  wordpress-web:

networks:
  webserver-net:
    name: webserver_network
...
