---
- name: Start Wordpress
  become: true
  docker_compose:
    project_name: wp
    definition:
      # BEGIN inline docker-compose.yml
      version: "3.7"
      services:
        wp:
          image: wordpress:latest
          container_name: wp
          restart: unless-stopped
          environment:
            - "WORDPRESS_DB_HOST=db"
            - "WORDPRESS_DB_USER=wordpress"
            - "WORDPRESS_DB_PASSWORD=wordpress"
            - "WORDPRESS_DB_NAME=wordpress"
            - "VIRTUAL_HOST={{ __domain_name }}"
            - "LETSENCRYPT_HOST={{ __domain_name }}"
            - "HSTS=max-age=31536000; includeSubDomains; preload"
            - "SSL_POLICY=Mozilla-Modern"
            - "ENABLE_IPV6=1"
          volumes:
            - /data/wp-web:/var/www/html
          networks:
            - webserver-net
      networks:
        webserver-net:
          name: webserver_network
      # END inline docker-compose.yml
  register: output

- name: Print docker-compose output
  debug:
    var: output
...
