---
- name: Create directory to hold Docker Compose file
  file:
    path: "/home/{{ ansible_user }}/ansible-docker/wordpress"
    state: directory

- name: Copy Docker Compose file
  template:
    src: docker-compose.yml
    dest: "/home/{{ ansible_user }}/ansible-docker/wordpress/docker-compose.yml"

- name: Pull and deploy compose stack
  become: true
  docker_compose:
    project_src: "/home/{{ ansible_user }}/ansible-docker/wordpress"
    build: true
    pull: true
    recreate: always
    remove_orphans: true
    restarted: true
...
