---
- hosts: all
  name: Docker on Ubuntu
  gather_facts: true
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  pre_tasks:
    - name: Show kernel version
      command: uname -a
      register: kernelver
      changed_when: false
    - debug: msg="{{ kernelver.stdout }}"

  roles:
    - packages
    - docker
    - reboot

  post_tasks:
    - name: Show kernel version
      command: uname -a
      register: kernelver
      changed_when: false
    - debug: msg="{{ kernelver.stdout }}"
...
