---
- name: Update all packages
  become: true
  dnf:
    # I don't really like this. This is ugly. But it's what the docs suggest for DNF upgrades (?!)
    name: "*"
    state: latest
  tags:
    - skip_ansible_lint

- name: Install useful packages
  become: true
  dnf:
    name:
      - fail2ban
    update_cache: true
    state: present

- name: Reboot box if kernel/libs updated and requested by the system
  become: true
  shell: /sbin/shutdown -r now 'Rebooting box to update system libs/kernel as needed'
  args:
    removes: /var/run/reboot-required
  async: 300
  poll: 0
  ignore_errors: true
  changed_when: false
  register: rebootafterupdates
  tags:
    - skip_ansible_lint

- name: Wait 600 seconds for target connection to become reachable/usable
  wait_for_connection:
  when: rebootafterupdates.changed
  tags:
    - skip_ansible_lint
...
