---
- name: Ensure Pi-Hole config directory exists
  file:
    path: "/home/{{ ansible_user }}/pihole/"
    state: directory

- name: Copy nginx.conf
  copy:
    src: nginx-public-resolver.conf
    dest: "/home/{{ ansible_user }}/pihole/nginx-public-resolver.conf"

- name: Git checkout the Nginx javascript code that translates DoH syntax into what we need (we refer to this in nginx.conf)
  git:
    repo: https://github.com/TuxInvader/nginx-dns.git
    dest: "/home/{{ ansible_user }}/pihole/nginx-dns"
    clone: true
  tags:
    - skip_ansible_lint  # Otherwise it complains we haven't checked out a specific branch

- name: Ensure Pi-Hole compose directory exists
  file:
    path: "/home/{{ ansible_user }}/ansible-docker/pihole/"
    state: directory

- name: Copy Compose file
  template:
    src: docker-compose.yml
    dest: "/home/{{ ansible_user }}/ansible-docker/pihole/docker-compose.yml"

- name: Start Pi-Hole via compose file
  become: true
  docker_compose:
    project_src: "/home/{{ ansible_user }}/ansible-docker/pihole/"
    pull: true
    recreate: always
    remove_orphans: true
    restarted: true
...
