---
- name: Start MySQL database
  become: true
  docker_compose:
    project_name: db
    definition:
      # BEGIN inline docker-compose.yml
      version: "3.7"
      services:
        db:
          image: mysql:8
          command: "--default-authentication-plugin=mysql_native_password"
          container_name: db
          restart: unless-stopped
          environment:
            - "MYSQL_ROOT_PASSWORD=somewordpress"
            - "MYSQL_DATABASE=wordpress"
            - "MYSQL_USER=wordpress"
            - "MYSQL_PASSWORD=wordpress"
          volumes:
            - /data/wp-db:/var/lib/mysql
          networks:
            - webserver-net
      networks:
        webserver-net:
          name: webserver_network
  register: output

- name: Print docker-compose output
  debug:
    var: output

- name: Pause for 3 minutes to allow database to start fully (should suffice even on a slow system)
  pause:
    minutes: 3
...
