---
- name: Create dir to hold acme.sh config
  file:
    path: ~/certs
    state: directory

# This step will fail unless ~/.ssh/acme_sh_account.conf exists on the local system
- name: Copy acme.sh config (incl. Cloudflare DNS API tokens) to server
  copy:
    src: ~/.ssh/acme_sh_account.conf
    dest: ~/certs/account.conf

- name: Generate a cert for DoH resolver
  become: true
  docker_container:
    name: acme.sh
    image: neilpang/acme.sh
    state: started
    auto_remove: true
    volumes:
      - "/home/{{ ansible_user }}/certs:/acme.sh"
    command: "--issue --dns dns_cf -d {{ __hostname }}.{{ __domain }}"

- name: Create a root cronjob to run at 4 AM to renew cert
  become: true
  cron:
    name: "Renew cert"
    minute: "0"
    hour: "4"
    job: 'docker run --rm -it -v "/home/{{ ansible_user }}/certs":"/acme.sh" neilpang/acme.sh --cron'

# We'll probably also need a cronjob to run after that to reload the Nginx config to actually pick up the new cert if we have one
...
