---
- name: Add the Docker CE Repo
  become: true
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: true
    enabled: true
  tags:
    - docker

- name: Install Docker, and Pip3
  become: true
  yum:
    name:
      - docker-ce
      - python3-pip
    update_cache: true
    state: present
  tags:
    - docker

- name: Enable Docker service
  become: true
  systemd:
    name: docker
    enabled: true
  tags:
    - docker

- name: Update Pip
  become: true
  pip:
    name: pip
    state: latest
    executable: pip3
  tags:
    - docker
    - skip_ansible_lint

- name: Install Python libraries for managing Docker (via Pip3)
  become: true
  pip:
    name:
      - docker
      - docker-compose
    state: present
    executable: pip3
  tags:
    - docker
...
