---
- name: Enable CentOS "Continuous Release" repo if we're still on CentOS <7.8 (we need the new libselinux-python3 package)
  become: true
  ini_file:
    dest: /etc/yum.repos.d/CentOS-CR.repo
    section: cr
    option: enabled
    value: "1"
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_version == "7.7"

- name: Clean yum cache
  become: true
  command: yum clean all
  args:
    warn: false
  tags:
    - skip_ansible_lint

- name: Update packages with yum
  become: true
  command: yum upgrade -y
  args:
    warn: false
  tags:
    - skip_ansible_lint

- name: Install useful packages (the libselinux-python* packages are needed for Ansible to handle contexts properly in the copy/file module)
  become: true
  package:
    name: [fail2ban, git, libselinux-python, libselinux-python3]
    update_cache: true
    state: present
...
